### ISSUE TITLE
[SUGESTÃO] Criar endpoint para salvar cadastro de matrículas de alunos

### ISSUE THREAD

**Issue by FelipeGaleao** [FelipeGaleao/fast-api-kafka#10]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

Prezados, sugerimos a criação de um novo endpoint para cadastrar matrículas de alunos no sistema. Espera-se que seja recebido um objeto contendo informações como nome do aluno, número de matrícula, curso, disciplinas e período letivo. É importante que o endpoint valide as informações recebidas antes de efetuar o cadastro no banco de dados. Seria interessante também retornar uma mensagem informando se a matrícula foi realizada com sucesso ou não.

## :heavy_check_mark: Benefícios 
Irá ajudar na automatização do processo de matrícula de alunos e facilitar o trabalho dos funcionários responsáveis pelo cadastro.

## :warning: Impactos Adicionais

É necessário garantir que as informações enviadas para o endpoint estejam corretas e completas, para evitar erros de cadastro no banco de dados.

## :information_source: Informações Adicionais

- Versão do software: v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by VitorLameirao** [comment]
Olá Maycon,

Sua sugestão é de vital importância para o nosso sistema e tenho convicção que irá gerar muito valor para nossos usuários.
Aguardo confirmação de outros membros da equipe para definirmos o momento para desenvolver essa Issue.
