### ISSUE TITLE
[SUGESTÃO] Criar endpoint para registrar horário de ponto

### ISSUE THREAD

**Issue by vitororb** [FelipeGaleao/fast-api-kafka#11]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

Se faz necessário criar um novo endpoint para registrar horário de ponto no Kafka. Espera-se que seja recebido um objeto contendo horario, pessoa e unidade. É necessário que as mensagens sejam publicadas em um novo tópico "comprovante_horario_ponto".

## :heavy_check_mark: Benefícios 

- Registro preciso de horas trabalhadas.
- Gestão de presença e ausência.
- Monitoramento de produtividade.
- Histórico de atividades.

## :warning: Impactos Adicionais

Criar um endpoint para registrar o horário de ponto em um sistema pode trazer diversos benefícios e ter várias finalidades. 

## :information_source: Informações Adicionais

- Versão do software: v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by FelipeGaleao** [comment]
Olá, Vitor. Vejo que sua sugestão é muito coerente com o nosso repositório.
Estou adicionando um critério de alta prioridade e marcando o @VitorLameirao para revisar.

**Comment by FelipeGaleao** [comment]
Pessoal, estive olhando. 
É interessante que no endpoint para registro de horário de ponto, seja necessário armazenarmos o setor do funcionário.
Conseguimos trabalhar nisso?

**Comment by MuriloMatias** [comment]
Olá @FelipeGaleao, todas as alterações foram realizadas. Fiz mais algumas alterações que foram necessárias. Vou encerrar aqui, até a próxima meus amigos.
