### ISSUE TITLE
[SUGESTÃO] Criar endpoint para escrita de mensagens no tópico "Comprovante_de_matriculas" do Kafka.

### ISSUE THREAD

**Issue by MuriloMatias** [FelipeGaleao/fast-api-kafka#12]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

Pessoal, precisamos de um endpoint para permitir a escrita de mensagens no tópico de "comprovantes_de_matricula" do Kafka. O principal objetivo é armazenar informações referentes à geração de comprovante de matrícula em tempo real, permitindo o monitoramento e análise dessas informações posteriormente. 

## :heavy_check_mark: Benefícios 

A criação deste novo endpoint terá impacto na arquitetura geral do sistema, já que será necessário integrá-lo com outras funcionalidades relacionadas à gestão de matrículas e ao monitoramento e análise das informações geradas. É importante considerar possíveis falhas na comunicação e garantir que nenhuma mensagem seja perdida durante o processo.

Sempre lembrar de Testar o endpoint e garantir o correto funcionamento.
## :warning: Impactos Adicionais

Criar um novo endpoint para escrita de mensagens no tópico "comprovante_horario_ponto"

## :information_source: Informações Adicionais

- Versão do software: v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by FelipeGaleao** [comment]
Olá, @MuriloMatias. Vejo que sua sugestão é de grande valor ao projeto. Estou marcando o @CaueMaldonadoLima para revisar sua sugestão. Estou definindo como prioridade média. Por mim, acredito que as solicitações terão um grande impacto positivo no projeto.

**Comment by vitororb** [comment]
Boa noite @FelipeGaleao e @MuriloMatias, ao revisar a issue eu sugiro que coloquemos mais um atributo com o nome codigo_matricula.

O que vocês acham @VitorLameirao e @CaueMaldonadoLima?

**Comment by VitorLameirao** [comment]
Boa noite @FelipeGaleao, @MuriloMatias e @VitorORBrandao, acho válido a sugestão, irei começar o desenvolvimento da mesma.

**Comment by FelipeGaleao** [comment]
Excelente, sugestão @VitorORBrandao. Sugiro que os ajustes seja realizado no arquivo main.py.

**Comment by CaueMaldonadoLima** [comment]
Boa Tarde @FelipeGaleao @VitorLameirao @MuriloMatias @VitorORBrandao, acredito que seja uma ótima sugestão.

**Comment by VitorLameirao** [comment]
Issue desenvolvida.
