### ISSUE TITLE
[SUGESTÃO] Criar endpoint de cadastrar professor

### ISSUE THREAD

**Issue by vitororb** [FelipeGaleao/fast-api-kafka#21]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

Este endpoint é responsável por cadastrar um novo professor no sistema. O cadastro de professor requer o envio dos dados necessários para criar um novo registro de professor, como nome, email, especialização, entre outros.

## :heavy_check_mark: Benefícios 

- Consistência de dados.
- Rastreabilidade.
- Separação de responsabilidades.

## Implementação :wrench:

**Parâmetros de entrada:**
- name (string): O nome completo do professor.
- email (string): O endereço de email do professor.
- specialization (string): A especialização ou área de atuação do professor.

**Resposta de Sucesso:**
Caso o professor seja cadastrado com sucesso, o endpoint retornará o código de status HTTP 201 (Created) juntamente com os dados do professor cadastrado.

## :information_source: Informações Adicionais

- Versão do software: v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by FelipeGaleao** [comment]
Vitor, vejo que sua sugestão é interessante. Mas não será necessário nesse momento.

**Comment by VitorLameirao** [comment]
@FelipeGaleao e @VitorORBrandao, acredito que precisaremos adicionar novos parâmetros nesse endpoint, como "CTPS" e "Telefone".

O que acham @CaueMaldonadoLima e @MuriloMatias?

**Comment by CaueMaldonadoLima** [comment]
Acredito que no momento atual não é algo muito relevante para o funcionamento do código, o que você acha @MuriloMatias ?

**Comment by MuriloMatias** [comment]
Olá @VitorLameirao, acredito que pode vir a ser útil. Porém, como estamos focando em outras coisas nesse momento, essa discussão deve ficar para o futuro.
