### ISSUE TITLE
[SUGESTÃO] Criar novo endpoint para recuperar dados referentes a matrícula. 

### ISSUE THREAD

**Issue by MuriloMatias** [FelipeGaleao/fast-api-kafka#22]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

Olá amigos, agora que já temos um endpoint para realização do cadastro da matrícula, precisamos de um endpoint para recuperar esses dados do kafta. Sempre verifique se a pessoa que está solicitando essas informações possui as credenciais necessárias para isso. 

## :heavy_check_mark: Benefícios 

Com esse novo endpoint, será possível recuperar informações referentes a matrícula que serão necessárias para o funcionamento do nosso sistema como um todo. 

## :warning: Impactos Adicionais

Verificar se a informação que está buscando está no banco para evitar erros ou informações incorretas. 

## :information_source: Informações Adicionais

- Versão do software: v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by FelipeGaleao** [comment]
Murilo, vejo que sua sugestão é boa. Entretanto, no momento, não faz sentido aplicarmos no código.

**Comment by CaueMaldonadoLima** [comment]
Acredito que seja necessário adicionar essa funcionalidade ao código

**Comment by VitorLameirao** [comment]
@CaueMaldonadoLima, acredito que no momento não temos a necessidade dessa funcionalidade no sistema, ela é muito custosa e não agrega tanto valor.

**Comment by vitororb** [comment]
@VitorLameirao concordo, não é necessário a implementação dessa funcionalidade no sistema.
