### ISSUE TITLE
[BUG] Endpoint de editar usuário não está funcionando

### ISSUE THREAD

**Issue by CaueMaldonadoLima** [FelipeGaleao/fast-api-kafka#23]
# :bug: Report de Bugs

Olá! Encontramos um bug no nosso software e gostaríamos de reportá-lo para que possa ser corrigido o mais rápido possível.

#  :mag_right: Descrição do Bug

O Endpoint de edição de usuário está funcionando de maneira incorreta ao clicar na aba de configurações e tentar editar perfil.

# :thought_balloon: Comportamento Esperado

Ao clicar em "Editar perfil" o usuário deve ser capaz de editar suas informações, por exemplo, alterar a foto de perfil. 

# :thought_balloon: Comportamento Atual

O usuário não consegue alterar informações básicas como a sua foto de perfil

# :information_source: Informações Adicionais

- Versão do software: v1.0.0 
- Agradecemos pela atenção e estamos à disposição para qualquer esclarecimento adicional.

**Comment by FelipeGaleao** [comment]
Caue, atualmente não temos nenhum endpoint relacionado a report de bugs.
Estou fechando essa Issue.
