### ISSUE TITLE
[SUGESTÃO] Adicionar fluxo aos mockups do figma

### ISSUE THREAD

**Issue by CaueMaldonadoLima** [FelipeGaleao/fast-api-kafka#24]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

Acredito que seja de grande importância adicionar fluxo aos mockups do figma.

## :heavy_check_mark: Benefícios 

- Aumenta a coesão dos mockups
- Exemplifica de maneira mais clara a funcionalidade de cada parte do projeto

Implementação :wrench:

- Adicionar fluxo aos botões do protótipo

## :warning: Impactos Adicionais

- Mantém a equipe mais coesa
- Diminui a ambiguidade 

## :information_source: Informações Adicionais

- Verificar se o fluxo está de acordo com as telas já criadas e com a documentação

- Versão do software: v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by FelipeGaleao** [comment]
Como não estamos utilizando Figma, estou fechando essa Issue.
