### ISSUE TITLE
[SUGESTÃO] Criar endpoint para criação de requisição acadêmica. 

### ISSUE THREAD

**Issue by MuriloMatias** [FelipeGaleao/fast-api-kafka#31]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

Olá amigos, acredito que precisamos de uma nova funcionalidade para o nosso sistema. Precisamos de uma funcionalidade permitindo que um estudante faça uma requisição acadêmica. Essa requisição precisa receber um objeto contendo o tipo de requisição, data, número da matrícula, nome do estudante e a descrição da requisição. Lembrando que precisamos de uma mensagem de retorno confirmando a se a requisição foi feita com sucesso ou não.

## :heavy_check_mark: Benefícios 

- Permitir que o estudante faça requisições a secretária de curso.
- Diminuir o tempo para conseguir a documentação necessária.
- Trocar informações referentes a matrícula. 

## :warning: Impactos Adicionais

Verificar se as informações vindas no endpoint estão corretas e completas, evitando erros cadastro da requisição no banco.

## :information_source: Informações Adicionais

- Versão do software:  v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by FelipeGaleao** [comment]
Olá, Murilo. Vejo que essa Issue é necessária. Podemos seguir com o desenvolvimento dela.
