### ISSUE TITLE
[SUGESTÃO] Melhoria na mensagem do consumer

### ISSUE THREAD

**Issue by FelipeGaleao** [FelipeGaleao/fast-api-kafka#4]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

Atualmente, a mensagem de log do consumer é bastante genérica e não fornece informações significativas sobre o que está acontecendo no sistema. Isso pode dificultar a detecção de problemas e tornar a depuração mais difícil, especialmente em ambientes complexos com muitos consumidores.

## :heavy_check_mark: Benefícios 

- Sugestão de melhoria: Adicionar informações mais detalhadas na mensagem de log do consumer, incluindo:
- O nome do tópico Kafka que está sendo processado pelo consumer.
- O número da partição do tópico que está sendo processada.
- O offset atual sendo processado pelo consumer.
- O registro específico que foi consumido e processado pelo consumer, incluindo o conteúdo dos dados.

## :warning: Impactos Adicionais

Com essas informações adicionais na mensagem de log do consumer, os desenvolvedores podem diagnosticar problemas de forma mais rápida e precisa, bem como entender melhor o comportamento do sistema em diferentes situações. Além disso, os logs mais detalhados podem ajudar a identificar possíveis gargalos de desempenho e outras áreas que possam ser otimizadas para melhorar a eficiência do sistema como um todo.

## :information_source: Informações Adicionais

- Versão do software: v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by vitororb** [comment]
Olá, Maycon
Concordo com a sua sugestão, acredito que vai ter impactos positivos para o entendimento dos consumidores.

**Comment by VitorLameirao** [comment]
Olá Maycon e Vitor,

Acredito que a sugestão realmente vá agregar para a nossa solução, porém, necessitamos analisar se realmente irá gerar valor para nossos usuários e comparar com o tempo necessário para o desenvolvimento dessa ISSUE.

**Comment by FelipeGaleao** [comment]
Issue implementada pelo @MuriloMatias
