### ISSUE TITLE
[SUGESTÃO] Modelo de severidade e/ou prioridade

### ISSUE THREAD

**Issue by vitororb** [FelipeGaleao/fast-api-kafka#5]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

No repositório não há modelo de severidade, sugiro utilizarmos a escala: Low, Medium e High nas issues, assim, definindo as Tags e severidade da mesma.

## :heavy_check_mark: Benefícios 

- Priorização de problemas.
- Comunicação clara.
- Tomada de decisões.
- Transparência e rastreabilidade.
- Melhoria contínua.

## Implementação :wrench:

Para a implementação deste modelo de severidade usaremos:
- Low: Problemas de baixa severidade que têm um impacto mínimo no funcionamento do sistema.
- Medium: Problemas que têm um impacto moderado no sistema ou em um grupo específico de usuários.
- High: Problemas críticos que afetam diretamente a funcionalidade principal do sistema, causando interrupção ou perda de dados.

## :warning: Impactos Adicionais

Ao atribuir uma severidade aos problemas, há uma maior responsabilidade e prestação de contas para a equipe de desenvolvimento em relação à resolução desses problemas. Isso cria um ambiente em que os membros da equipe são incentivados a tomar medidas para resolver as questões de maior gravidade e garantir a qualidade do software.

## :information_source: Informações Adicionais

- Versão do software: v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by FelipeGaleao** [comment]
Olá, @VitorORBrandao. Vejo que sua sugestão é coerente, entretanto, você pode ajustar as labels em Português?
Estou marcando meu par @MuriloMatias para conseguir te ajudar!

**Comment by MuriloMatias** [comment]
Olá @FelipeGaleao. Conte comigo para o que for necessário, acredito que podemos adicionar um nível a mais de severidade. Podemos adicionar o nível Critical para tratar de problemas que bloqueiam o funcionamento do software.
