### ISSUE TITLE
[SUGESTÃO] Controle de Versões (commit semântico)

### ISSUE THREAD

**Issue by vitororb** [FelipeGaleao/fast-api-kafka#7]
# :bulb: Sugestão 

Olá! Gostaríamos de compartilhar uma sugestão para o nosso software.

## :thought_balloon: Descrição da Sugestão

Conventional Commits é uma convenção para criar mensagens de commit padronizadas e semânticas. Essa convenção visa fornecer um formato consistente e significativo para as mensagens de commit, permitindo que as ferramentas automatizadas interpretem e analisem facilmente as alterações realizadas no código-fonte.

## :heavy_check_mark: Benefícios 

- Comunicação clara e consistente.
- Facilita a revisão de código.
- Melhoria da colaboração em equipe.
- Facilidade na geração de changelogs.

## Implementação :wrench:

Escolha um tipo apropriado para o seu commit, indicando o propósito das alterações. Alguns exemplos comuns de tipos são:
- feat: Adição de uma nova funcionalidade.
- fix: Correção de um bug.
- docs: Alterações relacionadas à documentação.
- style: Alterações de formatação, como espaços em branco, indentação, etc.
- refactor: Refatoração do código sem alterar o comportamento.

## :warning: Impactos Adicionais

- Padronização e consistência.
- Melhoria na documentação técnica.
- Pesquisabilidade e navegabilidade.

## :information_source: Informações Adicionais

- Versão do software: v1.0.0
Agradecemos pela atenção e esperamos por sua avaliação dessa sugestão!

**Comment by FelipeGaleao** [comment]
Boa, Vitor.
Acredito que realmente é necessário adotarmos um modelo de commit semantico.

Você pode criar a documentação e abrir um PR para nós?

**Comment by vitororb** [comment]
Ok Maycon, vou fazer isso.

**Comment by FelipeGaleao** [comment]
@VitorORBrandao Acredito que devemos melhorar a documentação...
Você consegue trazer exemplos de commit semantico?

**Comment by vitororb** [comment]
Opa @FelipeGaleao, boa ideia, vou resolver isso.

**Comment by MuriloMatias** [comment]
Também acho, gostei da ideia.

**Comment by FelipeGaleao** [comment]
Excelentes modificações. Estou fechando essa issue.
